### ISSUE TITLE
The best packaging framework

### ISSUE THREAD

**Issue by bnord** [DES-SL/EasyLens#14]
I've been watching this thread a little bit, and I've been installing some packages for other efforts. 

I have a few questions (let me know if this isn't the right place to ask this):

1. Is one packaging framework better than another? Or what are the strengths and weaknesses, amongst Anaconda, Pip and Homebrew, relevant for this project?

2. Can there be conflicts between those packaging frameworks when installing?

**Comment by drphilmarshall** [comment]
I use Homebrew for Mac OS X software, and pip and conda for python. Pip
seems to be teh current industry standard, but anaconda is getting so
widespread that often you can install software with either one. Simon knows
much more about package mgmt than I do though, clearly! I need to learn
though. I need to make HumVI a pip-installable package, for example.

**Comment by sibirrer** [comment]
packaging is not the right choice during development mode. We want to make sure that everyone is using the newest version on github. One can "pip install" also gitHub repos, see documentation.
Furthermore, the code relies on other software in my own github repo. proper packaging should avoid referencing to github repos.
