### ISSUE TITLE
"Worksheet" design

### ISSUE THREAD

**Issue by drphilmarshall** [DES-SL/EasyLens#4]
Tom recommends we design the IPython notebook as a "worksheet", i.e. as as instructions for new users ( he has high schoolers in mind ).

**Comment by drphilmarshall** [comment]
Some work started, see PR #5 for changes. More to come via the `issue/4/worksheet` branch.

**Comment by sibirrer** [comment]
I think this is done. The worksheet needs improvements in various directions. This should be contained in more specific issues.
