### ISSUE TITLE
SExtractor wrapper code

### ISSUE THREAD

**Issue by drphilmarshall** [DES-SL/EasyLens#6]
Error message
```
ImportError: No module named lenstronomy.DataAnalysis.Sextractor_wrapper.pysex
```
as seen in the [issue/4/worksheet branch notebook](https://github.com/DES-SL/EasyLens/blob/issue/4/worksheet/notebooks/ExampleWorksheet.ipynb)

Should this be checked in, @sibirrer ?

Also, I see `requirements.txt` is empty - we should start entering packages there, and then hook up travis-ci. I'll issue that.

**Comment by sibirrer** [comment]
the sextractor wrapper is now outsourced to sibirrer/pyextractor. This module needs to be installed on the local machine to run EasyLens. Mentioned it in the requirement.

**Comment by drphilmarshall** [comment]
Hmm. The error message I get from the notebook is unchanged, so maybe you only updated some of the import statements? Also, I think we need `pyextractor` to be pip installable, in order for EasyLens to work out of the box. Do you know how to do this? It's on my list of things to learn! :-)

**Comment by drphilmarshall** [comment]
BTW the `requirements.txt` file has to be machine readable: it is used by travis-ci to automatically install everything that EasyLens needs. I'll look to see if the travis build of the master branch is failing - yes, it is (see the badge on the [README](https://github.com/DES-SL/EasyLens/blob/master/README.md))

**Comment by sibirrer** [comment]
to install pyextractor (make it importable as a software package), type in the folder of pyextractor:
 -> python setup.py develope --user

my own github code won't be automatically be installed through the requirements.txt but you can manually install them on travis-ci

**Comment by sibirrer** [comment]
@drphilmarshall  I updated the requirements.txt such that it accepts github links of my repo. Hope it works. Otherwise let me know.

**Comment by drphilmarshall** [comment]
That's cool, I didn't know you could pip install a package directly from GitHub. However, your eggs are scrambled, it seems ;-)
```
pip install -r requirements.txt
--editable=git://github.com/sibirrer/pyextractor.git is not the right format; it must have #egg=Package
```
Can you see the travis log details in #5, for example?

**Comment by sibirrer** [comment]
thanks for pointing this out. I updated the requirements.txt. Has now explicit package names.
If working, please close issue

**Comment by sibirrer** [comment]
ok, there was a typo in the requirements.txt still. Fixed now.

**Comment by drphilmarshall** [comment]
Great, thanks! I made two further bits of progress, see #5. First is I cleaned up the `pyextract` code a bit, there were some rogue import statements in it (I submitted a pull request). Second is I condensed the notebook code a fair bit, to make it easier to stay with the worksheet narrative. It's currently erroring out on another possible `pyextract` bug - see what you think. Note that I reorganized the data folder to make the streamlining easy - if you're happy with it you could delete the `data/test_DESJ03305` folder.

**Comment by sibirrer** [comment]
implemented the suggestion and accepted pull request.
